// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatatablesController from "./datatables_controller"
application.register("datatables", DatatablesController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import TimeupController from "./timeup_controller"
application.register("timeup", TimeupController)
