version: '3.9'

services:
  postgresdb:
    image: postgres:15.4-alpine
    container_name: postgresdb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  minio:
    image: minio/minio:RELEASE.2021-08-17T20-53-08Z
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_HOST: ${MINIO_ROOT_HOST}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_MEDIA_STORE_BUCKET: ${MINIO_MEDIA_STORE_BUCKET}
    command: server --console-address :9001 /data
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  web:
    build: .
    container_name: sistema_teste
    volumes:
      - ./log:/home/app/sistema_teste/log
    secrets:
      - source: master_key
        target: /home/app/sistema_teste/config/master.key
    ports:
      - "8001:80"
    depends_on:
      - postgresdb
      - minio
      # - rabbitmq
      - elasticsearch
secrets:
  master_key:
    file: ./config/master.key
volumes:
  postgres-data:
  minio-data:
  es-data: