version: '3.9'

services:
  postgresdb:
    image: postgres:15.1-alpine
    container_name: postgresdb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  minio:
    image: minio/minio:RELEASE.2021-08-17T20-53-08Z
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001

    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_MEDIA_STORE_BUCKET: ${MINIO_MEDIA_STORE_BUCKET}
    command: server --console-address :9001 /data
volumes:
  postgres-data:
  minio-data:

