default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host:     <%= ENV.fetch("DB_HOST")%>
  username: <%= ENV.fetch("DB_USER_NAME")%>
  password: <%= ENV.fetch("DB_PASSWORD")%>
  port:     <%= ENV.fetch("DBPORT") { 5432 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DBNAME") { "test_crud_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DBTEST") { "test_crud_test" } %>

production:
  <<: *default
  pool:     <%= ENV.fetch("DATABASE_POOL") { 20 } %>
  database: <%= ENV['POSTGRES_DB'] %>
  host:     <%= ENV['POSTGRES_HOST'] { 5432 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>