test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

minio:
  service: S3
  endpoint: <%= ENV.fetch('MINIO_ROOT_HOST')  %>
  access_key_id: <%= ENV.fetch('MINIO_ROOT_USER') { Rails.application.credentials.dig(minio, :user) %>
  secret_access_key: <%= ENV.fetch('MINIO_ROOT_PASSWORD') { Rails.application.credentials.dig(minio, :password) %>
  bucket: <%= ENV.fetch('MINIO_MEDIA_STORE_BUCKET') { Rails.application.credentials.dig(minio, :bucket) %>
  region: <%= ENV.fetch('AWS_REGION') { Rails.application.credentials.dig(minio, :region) %>
  force_path_style: true

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>