test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

minio:
  service: S3
  endpoint: <%= ENV['MINIO_ROOT_HOST'] %>
  access_key_id: <%= ENV['MINIO_ROOT_USER'] %>
  secret_access_key: <%= ENV['MINIO_ROOT_PASSWORD'] %>
  bucket: <%= ENV['MINIO_MEDIA_STORE_BUCKET'] %>
  region: <%= ENV['AWS_REGION'] %>
  force_path_style: true

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>