test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: S3
  endpoint: <%= ENV['MINIO_ACCESS'] %>
  access_key_id: <%= ENV['MINIO_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['MINIO_SECRET_KEY'] %>
  bucket: <%= ENV['MINIO_BUCKET'] %>
  region: ENV['AWS_REGION']
  force_path_style: true
